In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
from scipy.interpolate import griddata
from matplotlib import cm

In [2]:
# 让图片中可以显示中文
plt.rcParams['font.sans-serif'] = 'SimHei'
# 让图片中可以显示负号
plt.rcParams['axes.unicode_minus'] = False

In [3]:
# 读取Excel文件，忽略前6行
df0 = pd.read_csv('~/视频/20240322.csv', skiprows=6)
df0 = df0.drop(df0.columns[[0,2,3,4,6]+list(range(-1, -5, -1))], axis=1)
display(df0.head())
df0_rows = int(df0.shape[0]/9)
df0_cols = int(df0.shape[1]-2)
df0_values = df0.values

,P1,P5,P7,P8,P9,P10,P11,P12,P13,P14,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,P38
0,0.5144,1.5,13768.680664,286696.812500,28747.720703,354003.71875,34314.933594,357846.5000,56136.917969,395813.1875,...,97280.148438,371894.75000,96071.804688,368650.34375,59487.933594,296156.00000,8303.420898,159177.484375,71481.867188,3.669561e+05
1,1.0290,1.5,15661.307617,239330.390625,30706.921875,278924.68750,35697.226562,279872.7500,56019.222656,327893.5000,...,97762.851562,365059.93750,96441.281250,363170.93750,58987.832031,288542.56250,5880.359375,130922.351562,62098.503906,3.350240e+05
2,1.5430,1.5,14526.572266,227596.468750,27759.197266,266642.81250,32271.853516,275117.9375,51267.171875,325726.9375,...,99005.960938,352817.65625,97583.656250,351476.68750,58434.101562,289191.40625,5149.017090,136740.640625,59760.777344,3.146491e+05
3,0.5144,2.0,36442.476562,552685.375000,57913.855469,754881.68750,64295.289062,780469.2500,93842.429688,892707.5000,...,130793.906250,845505.00000,129560.609375,842952.87500,87147.531250,708814.87500,50588.695312,621670.250000,153912.140625,1.021330e+06
4,1.0290,2.0,35045.921875,498700.343750,58710.476562,656219.56250,64407.519531,671388.8750,90042.953125,754463.6875,...,131359.234375,661598.06250,129916.445312,662650.75000,87981.367188,588829.75000,40036.625000,477864.031250,101340.085938,7.536669e+05

In [4]:
# 定义插值函数
def interpolate_surface(x, y, z):
    # 创建网格点
    xi = np.linspace(x.min(), x.max(), 100)
    yi = np.linspace(y.min(), y.max(), 100)
    xi, yi = np.meshgrid(xi, yi)
    
    # 进行插值
    zi = griddata((x, y), z, (xi, yi), method='cubic')
    return xi, yi, zi

# 循环处理每个子图
for j in range(df0_cols):
    for i in range(df0_rows):
        x = df0_values[i*9:(i+1)*9, 0].reshape(-1)
        y = df0_values[i*9:(i+1)*9, 1].reshape(-1)
        z = df0_values[i*9:(i+1)*9, j+2].reshape(-1) / 10000
        
        # 插值得到曲面
        xi, yi, zi = interpolate_surface(x, y, z)
        
        # 创建一个三维坐标系
        fig = plt.figure(figsize=(5,5))
        ax = fig.add_subplot(111, projection='3d')

        # 绘制曲面
        ax.plot_surface(xi, yi, zi, cmap=cm.coolwarm)

        jun_zui = '均值' if j%2==0 else '最值'
        # 绘制与zi=50相交的曲面
        # ax.contourf(xi, yi, zi, [50], colors='black', linestyles='solid', linewidths=3)
        if np.any(zi >=49): 
            ax.contourf(xi, yi, zi, levels=[49.9,50.1], colors='black')
        if np.any(zi >=195): 
            ax.contourf(xi, yi, zi, levels=[195.9,196.1], colors='green')
            print(f'{i*45}度缆绳{int(j/2)+1}张力{jun_zui}')

        # 绘制散点图
        ax.scatter(x, y, z)

        # 设置坐标轴标签
        ax.set_xlabel('流速(m/s)')
        ax.set_ylabel('波高(m)')
        ax.set_zlabel('缆绳张力(t)')
        plt.title(f'{i*45}度缆绳{int(j/2)+1}张力{jun_zui}')

        plt.subplots_adjust(left=0.1, right=0.8, top=0.9, bottom=0.1)

        # 保存图形
        plt.savefig(f'/home/shuai/pic2/{i*45}度缆绳{int(j/2)+1}张力{jun_zui}.jpg')

        # 关闭图形，以便下一次循环创建新的图形
        plt.close()

90度缆绳1张力最值
90度缆绳2张力最值
135度缆绳2张力最值
90度缆绳3张力最值
135度缆绳3张力最值
90度缆绳4张力最值
135度缆绳4张力最值
90度缆绳5张力最值
135度缆绳5张力最值
45度缆绳6张力最值
90度缆绳6张力最值
135度缆绳6张力最值
45度缆绳7张力最值
90度缆绳7张力最值
135度缆绳7张力最值
45度缆绳8张力最值
90度缆绳8张力最值
135度缆绳8张力最值
90度缆绳9张力最值
90度缆绳10张力最值
90度缆绳11张力最值
90度缆绳12张力最值
90度缆绳13张力最值
90度缆绳14张力最值
90度缆绳15张力最值
135度缆绳15张力最值
45度缆绳16张力最值
90度缆绳16张力最值
135度缆绳16张力最值

In [5]:
# 读取Excel文件，忽略前6行
df1 = pd.read_csv('~/视频/20240322.csv', skiprows=6)
df1 = df1.iloc[:, [1, 5]].join(df1.iloc[:, -4:])
display(df1.head())
df1_rows = int(df1.shape[0]/9)
df1_cols = int(df1.shape[1]-2)
df1_values = df1.values
display(df1_rows, df1_cols)

       P1   P5       P39       P40       P41       P42
0  0.5144  1.5  0.000000  0.000000  0.000000  0.000000
1  1.0290  1.5 -0.002867  0.139097  1.370941  1.545274
2  1.5430  1.5 -0.004080  0.134852  1.374937  1.532036
3  0.5144  2.0  0.217602  0.915120  1.349742  1.890763
4  1.0290  2.0  0.031626  0.335760  1.359569  1.723838

5

4

In [6]:
# 定义插值函数
def interpolate_surface(x, y, z):
    # 创建网格点
    xi = np.linspace(x.min(), x.max(), 100)
    yi = np.linspace(y.min(), y.max(), 100)
    xi, yi = np.meshgrid(xi, yi)
    
    # 进行插值
    zi = griddata((x, y), z, (xi, yi), method='cubic')
    return xi, yi, zi

# 循环处理每个子图
for j in range(df1_cols):
    for i in range(df1_rows):
        x = df1_values[i*9:(i+1)*9, 0].reshape(-1)
        y = df1_values[i*9:(i+1)*9, 1].reshape(-1)
        z = df1_values[i*9:(i+1)*9, j+2].reshape(-1)
        
        # 插值得到曲面
        xi, yi, zi = interpolate_surface(x, y, z)
        
        # 创建一个三维坐标系
        fig = plt.figure(figsize=(5,5))
        ax = fig.add_subplot(111, projection='3d')

        # 绘制曲面
        ax.plot_surface(xi, yi, zi, cmap=cm.coolwarm)

        heng_zong = '横荡' if int(j/2)==0 else '纵荡'
        jun_zui = '均值' if j%2==0 else '最值'
        # 绘制与zi=50相交的曲面
        if np.any(zi >=49): 
            ax.contourf(xi, yi, zi, levels=[49.9,50.1], colors='black')
        if np.any(zi >=195): 
            ax.contourf(xi, yi, zi, levels=[195.9,196.1], colors='green')
            print(f'{i*45}度船舶{heng_zong}{jun_zui}')

        # 绘制散点图
        ax.scatter(x, y, z)
        # 设置坐标轴标签
        ax.set_xlabel('流速(m/s)')
        ax.set_ylabel('波高(m)')
        ax.set_zlabel(f'{heng_zong}(m)')
        plt.title(f'{i*45}度船舶{heng_zong}{jun_zui}')

        plt.subplots_adjust(left=0.1, right=0.8, top=0.9, bottom=0.1)

        # 保存图形
        plt.savefig(f'/home/shuai/pic2/{i*45}度船舶{heng_zong}{jun_zui}.jpg')

        # 关闭图形，以便下一次循环创建新的图形
        plt.close()